# Generated by Django 5.1.6 on 2025-03-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='descrition',
            new_name='description',
        ),
    ]
